import React from 'react'

import Layout from '../components/layout'

export default () => (
  <Layout>
    <div className='mx-auto pb-10 px-8' style={{ maxWidth: 600 }}>
      <div className='text-xl mt-6'>Cookie Policy</div>
      <p>Updated at 2021-11-23</p>

      <div className='text-lg mt-6'>Definitions and key terms</div>
      <p>
        To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:
        <ul className='list-disc'>
          <li className='ml-10'>
            Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about
            you such as your language preference or login information.
          </li>
          <li className='ml-10'>
            Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Indigov, that is responsible for your information under this Cookie Policy.
          </li>
          <li className='ml-10'>
            Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Indigov and use the services.
          </li>
          <li className='ml-10'>
            Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the
            identification or identifiability of a natural person.
          </li>
          <li className='ml-10'>Service: refers to the service provided by Indigov as described in the relative terms (if available) and on this platform. </li>
          <li className='ml-10'>
            Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we
            think may interest you.
          </li>
          <li className='ml-10'>Website: site, which can be accessed via this URL: indigov.com</li>
        </ul>
      </p>

      <div className='text-lg mt-6'>Introduction</div>
      <p>
        This Cookie Policy explains how Indigov and its affiliates (collectively "Indigov", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you
        visit our website, including without limitation indigov.com and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains
        what these technologies are and why we use them, as well as the choices for how to control them.
      </p>

      <div className='text-lg mt-6'>What is a cookie?</div>
      <p>
        A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information
        about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.
      </p>

      <div className='text-lg mt-6'>Why do we use cookies?</div>
      <p>We use first party and/or third party cookies on our website for various purposes such as:</p>
      <ul className='list-disc'>
        <li className='ml-10'>To facilitate the operation and functionality of our website;</li>
        <li className='ml-10'>To improve your experience of our website and make navigating around them quicker and easier;</li>
        <li className='ml-10'>To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;</li>
        <li className='ml-10'>To analyze how our website is used and how best we can customize it;</li>
        <li className='ml-10'>To identify future prospects and personalize marketing and sales interactions with it;</li>
        <li className='ml-10'>To facilitate the tailoring of online advertising to your interests.</li>
        <li className='ml-10'>You: a person or entity that is registered with Indigov to use the Services.</li>
      </ul>

      <div className='text-lg mt-6'>What type of cookies does Indigov use?</div>
      <p>
        Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it
        expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years.
        Cookies placed by the website you’re visiting are called “first party cookies”.
      </p>
      <p>
        Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around
        the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.
      </p>
      <p>We use the following types of cookies in our website:</p>
      <div className='text-lg mt-6'>Essential Cookies</div>
      <p>
        We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie
        preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the
        Websites function.
      </p>
      <div className='text-lg mt-6'>Performance and Functionality Cookies</div>
      <p>
        These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality
        like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had
        logged in previously.
      </p>
      <div className='text-lg mt-6'>Analytics and Customization Cookies</div>
      <p>
        These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our
        website for you.
      </p>
      <p>
        We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further
        information on how Google collects and uses this data can be found at: https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics
        on our Websites by visiting: https://tools.google.com/dlpage/gaoptout.
      </p>
      <div className='text-lg mt-6'>Third Party Cookies</div>
      <p>
        Some cookies that have been set on our website are not set on a first party basis by Indigov. The Websites can be embedded with content from third parties to serve
        advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and
        functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the
        third party that originally set them.
      </p>
      <div className='text-lg mt-6'>How you can manage cookies?</div>
      <p>
        Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall
        user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide
        help pages relating to cookie management in their products.
      </p>
      <p>Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.</p>
      <ul className='list-disc'>
        <li className='ml-10'>Google Chrome</li>
        <li className='ml-10'>Internet Explorer</li>
        <li className='ml-10'>Mozilla Firefox</li>
        <li className='ml-10'>Safari (Desktop)</li>
        <li className='ml-10'>Safari (Mobile)</li>
        <li className='ml-10'>Android Browser</li>
        <li className='ml-10'>Opera</li>
        <li className='ml-10'>Opera Mobile</li>
      </ul>

      <div className='text-lg mt-6'>Blocking and disabling cookies and similar technologies</div>
      <p>
        Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website
        from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information
        (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or
        category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for
        more information.
      </p>

      <div className='text-lg mt-6'>Changes To Our Cookie Policy</div>
      <p>
        We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise
        required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they
        go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy,
        you can delete your account.
      </p>

      <div className='text-lg mt-6'>Your Consent</div>
      <p>By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.</p>
      <div className='text-lg mt-6'>Contact Us</div>
      <p>Don't hesitate to contact us if you have any questions regarding our Cookie Policy.</p>
      <ul className='list-disc'>
        <li className='ml-10'>Via this Address: 80 M St SE Washington, DC 20003</li>
        <li className='ml-10'>
          Or email us:
          <a className='underline' href='mailto:contact@indigov.com'>
            contact@indigov.com
          </a>
        </li>
      </ul>
    </div>
  </Layout>
)
